export const STATES = [
  { key: "AL", label: "Alabama", avgTemp: 62.8 },
  { key: "AK", label: "Alaska", avgTemp: 26.6 },
  { key: "AZ", label: "Arizona", avgTemp: 60.3 },
  { key: "AR", label: "Arkansas", avgTemp: 60.4 },
  { key: "CA", label: "California", avgTemp: 59.4 },
  { key: "CO", label: "Colorado", avgTemp: 45.1 },
  { key: "CT", label: "Connecticut", avgTemp: 49.0 },
  { key: "DE", label: "Delaware", avgTemp: 55.3 },
  { key: "FL", label: "Florida", avgTemp: 70.7 },
  { key: "GA", label: "Georgia", avgTemp: 63.5 },
  { key: "HI", label: "Hawaii", avgTemp: 70.0 },
  { key: "ID", label: "Idaho", avgTemp: 44.4 },
  { key: "IL", label: "Illinois", avgTemp: 51.8 },
  { key: "IN", label: "Indiana", avgTemp: 52.1 },
  { key: "IA", label: "Iowa", avgTemp: 47.8 },
  { key: "KS", label: "Kansas", avgTemp: 54.3 },
  { key: "KY", label: "Kentucky", avgTemp: 55.6 },
  { key: "LA", label: "Louisiana", avgTemp: 66.4 },
  { key: "ME", label: "Maine", avgTemp: 41.0 },
  { key: "MD", label: "Maryland", avgTemp: 54.2 },
  { key: "MA", label: "Massachusetts", avgTemp: 47.9 },
  { key: "MI", label: "Michigan", avgTemp: 44.4 },
  { key: "MN", label: "Minnesota", avgTemp: 41.2 },
  { key: "MS", label: "Mississippi", avgTemp: 63.4 },
  { key: "MO", label: "Missouri", avgTemp: 54.5 },
  { key: "MT", label: "Montana", avgTemp: 42.7 },
  { key: "NE", label: "Nebraska", avgTemp: 48.8 },
  { key: "NV", label: "Nevada", avgTemp: 49.9 },
  { key: "NH", label: "New Hampshire", avgTemp: 43.8 },
  { key: "NJ", label: "New Jersey", avgTemp: 52.7 },
  { key: "NM", label: "New Mexico", avgTemp: 53.4 },
  { key: "NY", label: "New York", avgTemp: 45.4 },
  { key: "NC", label: "North Carolina", avgTemp: 59.0 },
  { key: "ND", label: "North Dakota", avgTemp: 40.4 },
  { key: "OH", label: "Ohio", avgTemp: 50.7 },
  { key: "OK", label: "Oklahoma", avgTemp: 59.6 },
  { key: "OR", label: "Oregon", avgTemp: 48.4 },
  { key: "PA", label: "Pennsylvania", avgTemp: 48.8 },
  { key: "RI", label: "Rhode Island", avgTemp: 50.1 },
  { key: "SC", label: "South Carolina", avgTemp: 62.4 },
  { key: "SD", label: "South Dakota", avgTemp: 45.2 },
  { key: "TN", label: "Tennessee", avgTemp: 57.6 },
  { key: "TX", label: "Texas", avgTemp: 64.8 },
  { key: "UT", label: "Utah", avgTemp: 48.6 },
  { key: "VT", label: "Vermont", avgTemp: 42.9 },
  { key: "VA", label: "Virginia", avgTemp: 55.1 },
  { key: "WA", label: "Washington", avgTemp: 48.3 },
  { key: "WV", label: "West Virginia", avgTemp: 51.8 },
  { key: "WI", label: "Wisconsin", avgTemp: 43.1 },
  { key: "WY", label: "Wyoming", avgTemp: 42.0 },
];
